# Generated by Django 5.2.17 on 2026-08-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='horario_fim',
            new_name='horario',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='finalizado',
        ),
    ]
