# Generated by Django 5.2.17 on 2026-08-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_horario_fim_evento_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='horario_inicio',
        ),
    ]
